### ISSUE TITLE
negli utenti random manca il codice fiscale

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#103]
chiedo l'attributo codice fiscale e mi da:
```
saml2.s_utils.MissingValue
saml2.s_utils.MissingValue: Required attribute missing: fiscalnumber

Traceback (most recent call last)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/srv/testenv2/env/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/srv/testenv2/spid-testenv.py", line 1405, in login
identity = filter_on_demands(identity, rava, oava)
File "/srv/testenv2/env/lib/python3.5/site-packages/saml2/assertion.py", line 170, in filter_on_demands
raise MissingValue("Required attribute missing: %s" % (attr,))
saml2.s_utils.MissingValue: Required attribute missing: fiscalnumber
```

in effetti in `conf/users.json` manca il campo corrispondente ...

**Comment by simevo** [comment]
la mia fix genera questo:
```
"fiscalNumber": "CFFMTG26Q91X850X",
"fiscalNumber": "WBPYOB39E41E453R",
"fiscalNumber": "AQTNOH28D88P547Y",
"fiscalNumber": "VQLYJN14D65E727E",
"fiscalNumber": "LMXSJT93R00F094E",
"fiscalNumber": "AGQMOR74Y81M019C",
"fiscalNumber": "BOBMUL14M05J118L",
"fiscalNumber": "RJBJFI14B89N016T",
"fiscalNumber": "UCONLQ82Z28U093Z",
"fiscalNumber": "FRVRVK57N75V484C",
```
