### ISSUE TITLE
UnboundLocalError: local variable 'issuer' referenced before assignment

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#127]
```
[2018-08-14 10:18:52,047] DEBUG in server: req: '<Request 'http://idp.simevo.com/slo?SAMLRequest=nVLPS8MwFL7vryi5b03XrksfXUGYSmFu6sSDF4ltpoE2qXmp6H9v1uwwhg4xx%2B%2B979cjOfK26WClX3Vv78V7L9COAvc%2B20YhDNMF6Y0CzVEiKN4KBFvB9uJmBdMJhc5oqyvdkBPaeRZHFMZKrTytXC7IZn252lyX6%2Bc0ruY8SbMoniVJnEaMxaISjLMsmdezTNR8l9Ise%2FHUR2HQ6SyIkz2IIfaiVGi5sg6mERtTNo6SB8ogYjCbPvm9pesqFbcD%2B83aDiEMZd1NULbiQ08q3YbYaFIM2%2Fm%2BFAzaJrjSpuX2fMU9IuvxblgFoay0XyRYO%2FSu543cSWG8rXPFbnrkCoxSSorfZ3l4FOY43l69XAbb27%2Fb%2FL9L8fPNDuF8FB9u5LGTf1Z8Aw%3D%3D&RelayState=http%3A%2F%2Fsp2.simevo.com%3A8000%2Flogout.php&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=TK3Q3pgvUEVY%2BjWtXLNBFfhybBE%2FexOyRgpSyI25cavZPaBwrJILOq8qu6tuez7K9rw46rFZ34FHzYrSrSCLK%2B92tELVPIY7YdAKiuPU55ful81bYowcrdO5wBSmghlndUl1LiHVkdJqwNS%2BiE9xPBrbDvpMJucDCuYJCNVex%2BVIrs6XpHaGEAtiUQyQXkN6IVwG9FBEyNIzk6beZ0gw%2Bz62L1AA6qeMxfZYlcA8z%2FtO9ZU38wm7k77IjLCbpprgz74hidY4e4ezGQD%2BcLvPspeMecYCgTOd02A%2Fntr1tnaiRxpwpJkk6JZ4uWXxyUyPmMIh%2FN7PK6T0fCFFf%2FNArg%3D%3D' [GET]>'
[2018-08-14 10:18:52,053] DEBUG in server: LogoutRequest: 
<ns0:LogoutRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://idp.simevo.com/slo" ID="ONELOGIN_63c7a46913544361883ece8a8947d59edaf6099b" IssueInstant="2018-08-14T08:18:52Z" Version="2.0">
    <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://sp2.simevo.com:8000">http://sp2.simevo.com:8000</ns1:Issuer><ns1:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" SPNameQualifier="http://sp2.simevo.com:8000">https://idp.simevo.com</ns1:NameID></ns0:LogoutRequest>

127.0.0.1 - - [14/Aug/2018 10:18:52] "GET /slo?SAMLRequest=nVLPS8MwFL7vryi5b03XrksfXUGYSmFu6sSDF4ltpoE2qXmp6H9v1uwwhg4xx%2B%2B979cjOfK26WClX3Vv78V7L9COAvc%2B20YhDNMF6Y0CzVEiKN4KBFvB9uJmBdMJhc5oqyvdkBPaeRZHFMZKrTytXC7IZn252lyX6%2Bc0ruY8SbMoniVJnEaMxaISjLMsmdezTNR8l9Ise%2FHUR2HQ6SyIkz2IIfaiVGi5sg6mERtTNo6SB8ogYjCbPvm9pesqFbcD%2B83aDiEMZd1NULbiQ08q3YbYaFIM2%2Fm%2BFAzaJrjSpuX2fMU9IuvxblgFoay0XyRYO%2FSu543cSWG8rXPFbnrkCoxSSorfZ3l4FOY43l69XAbb27%2Fb%2FL9L8fPNDuF8FB9u5LGTf1Z8Aw%3D%3D&RelayState=http%3A%2F%2Fsp2.simevo.com%3A8000%2Flogout.php&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=TK3Q3pgvUEVY%2BjWtXLNBFfhybBE%2FexOyRgpSyI25cavZPaBwrJILOq8qu6tuez7K9rw46rFZ34FHzYrSrSCLK%2B92tELVPIY7YdAKiuPU55ful81bYowcrdO5wBSmghlndUl1LiHVkdJqwNS%2BiE9xPBrbDvpMJucDCuYJCNVex%2BVIrs6XpHaGEAtiUQyQXkN6IVwG9FBEyNIzk6beZ0gw%2Bz62L1AA6qeMxfZYlcA8z%2FtO9ZU38wm7k77IjLCbpprgz74hidY4e4ezGQD%2BcLvPspeMecYCgTOd02A%2Fntr1tnaiRxpwpJkk6JZ4uWXxyUyPmMIh%2FN7PK6T0fCFFf%2FNArg%3D%3D HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/testenv2/testenv/server.py", line 867, in single_logout_service
    req_info, 'logout', _binding, **extra
  File "/srv/testenv2/testenv/server.py", line 338, in _check_spid_restrictions
    msg.message, action, binding, **kwargs
  File "/srv/testenv2/testenv/parser.py", line 457, in parse
    if schema is None else schema
  File "/srv/testenv2/testenv/parser.py", line 430, in get_schema
    Attr('name_qualifier', default=issuer, func=check_url),
UnboundLocalError: local variable 'issuer' referenced before assignment
```

**Comment by simevo** [comment]
non siamo più in grado di testare questo perché è un problema incontrato con simevo/spid-php2 che è on hold (il focus si è spostato sulla lib core italia/spid-php-lib) e al momento non più funzionante con il testenv2 attuale; chiudo e poi evtl riapriamo se il caso
