### ISSUE TITLE
AuthnRequest: errore quando manca l'elemento Issuer

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#133]
Inviando una AuthnRequest priva di elemento `<Issuer>`:

```xml
<saml2p:AuthnRequest ForceAuthn="false" AttributeConsumingServiceIndex="1" AssertionConsumerServiceURL="http://localhost:3000/spid-sso" ID="_980c46de183f4818b1f765dfb22fd1dc" Destination="http://localhost:8088/sso" IssueInstant="2018-08-18T06:57:22Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

il testenv2 genera questo errore:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/testenv/server.py", line 474, in single_sign_on_service
    sp_id = authn_req.issuer.text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by sanjioh** [comment]
Ciao @alexrj, questa issue dovrebbe essere corretta in #136
