### ISSUE TITLE
RelayState non ritornato al SP nella richiesta POST contenente l'input SAMLResponse

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#135]
Background: integrazione del server spid-testenv2 nel software di IAM Keycloak (https://github.com/keycloak/keycloak) come IdP esterno cui delegare l'autenticazione. In questo caso Keycloak si comporta come SP verso spid-testenv2.

Problema: Keycloack invia una richiesta POST contenente un valore nel parametro RelayState:
![image](https://user-images.githubusercontent.com/10044374/44453845-5a49e780-a5fa-11e8-8abe-a23e2113185b.png)
Questo parametro dovrebbe essere restituito as-is da spid-testenv2 nella richiesta POST verso l'ACS del SP (in questo caso appunto Keycloak). Da https://en.wikipedia.org/wiki/SAML_2.0:

> The RelayState token is an opaque reference to state information maintained at the service provider.
[...]
> The value of the RelayState parameter has been preserved

Invece, viene restituito vuoto, contravvenendo alla specifica SAML2:
![image](https://user-images.githubusercontent.com/10044374/44454076-dcd2a700-a5fa-11e8-978d-86d4da6eb92f.png)

Di conseguenza Keycloak segnala un errore di tipo Invalid request.

Nel caso sono disponibile per la risoluzione dell'errore, per esempio fornendo la build customizzata di Keycloak compatibile con spid-testenv2 (dato che la AuthnRequest del repo master non supera alcune delle validazioni previste da spid).

**Comment by sanjioh** [comment]
Ciao, questa issue dovrebbe essere risolta nell'ultimo master, puoi cortesemente riprovare?
Grazie

**Comment by sanjioh** [comment]
@marcoz-tsn Ciao, riesci a darci feedback riguardo questa issue? Grazie :)

**Comment by marcoz-tsn** [comment]
@sanjioh Ciao, ci sto provando, ma la mia condizione di test non funziona da un po'. Nello specifico sono bloccato da #165 e da un errore più specifico ancora:

Elemento | Dettagli errore
-- | --
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest - attribute: IsPassive | false extra keys not allowed

**Comment by sanjioh** [comment]
Ciao @marcoz-tsn,
ora che #165 e' chiusa, il problema di questa issue si presenta ancora?
Per quanto riguarda l'attributo `IsPassive`, in teoria, secondo le specifiche tecniche, non dovrebbe essere presente: https://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#id1
Grazie per il feedback :)

**Comment by marcoz-tsn** [comment]
Ciao @sanjioh, ho rimosso l'attributo dalla AuthnRequest; ora dà questo errore:

`builtins.AttributeError
AttributeError: no such child: {http://www.w3.org/2000/09/xmldsig#}X509Data

Traceback (most recent call last)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/testenv/server.py", line 288, in single_sign_on_service
spid_request = self._parse_message(action='login')
File "/app/testenv/server.py", line 225, in _parse_message
return self._handle_http_post(action)
File "/app/testenv/server.py", line 264, in _handle_http_post
HTTPPostSignatureVerifier(cert, request_data).verify()
File "/app/testenv/crypto.py", line 210, in verify
self._ensure_supported_algorithm()
File "/app/testenv/crypto.py", line 215, in _ensure_supported_algorithm
self._check_algorithm_deprecation_list()
File "/app/testenv/crypto.py", line 219, in _check_algorithm_deprecation_list
sig_alg = self._extract('sig_alg')
File "/app/testenv/crypto.py", line 233, in _extract
self._xml_doc[SIGNATURE][KEY_INFO][X509_DATA]
File "src/lxml/objectify.pyx", line 288, in lxml.objectify.ObjectifiedElement.__getitem__
 
File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
 
AttributeError: no such child: {http://www.w3.org/2000/09/xmldsig#}X509Data`

**la Request è**:
`<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns="urn:oasis:names:tc:SAML:2.0:assertion" AssertionConsumerServiceURL="http://localhost:8081/auth/realms/tecsis/broker/SPID/endpoint" Destination="http://spid-testenv2:8088" ForceAuthn="false" ID="ID_fcf966c4-c52d-4139-9262-9415a193023d" IssueInstant="2018-10-02T15:59:20.723Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://localhost:8081/auth/realms/tecsis">http://localhost:8081/auth/realms/tecsis</saml:Issuer><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><dsig:Reference URI="#ID_fcf966c4-c52d-4139-9262-9415a193023d"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><dsig:DigestValue>4d0HypDG9fG1opXDzAo7xAApEgszQstB5vd11iVys/I=</dsig:DigestValue></dsig:Reference></dsig:SignedInfo><dsig:SignatureValue>SCNjPzrk9gm+R4+JKBNOc/Oo7PktnwHI6RXAErfs1hWHIjkZiFOJCTuXRWuiywCSKgFDkkuZ0FZBw6tpNt2hrgoirGJ+cYvkhYCQiblrccD3oZFz8vU3Ik6VHHvexs7qlYhbNxb5L2KNgsstI+4EzAAC+NSBkiQIXXMZaIuEc4WStesZBDnQn0sli2zjh5XdWWWFYcwtTQr4020WjJif668q4z9oTk8Nymt2mziWB30qy4ivShkiisDBi3aXxbXq0W0QdkBGo4zXysSjpTMlXcoxTWFaPLFIpl49JvVGx1rjjaRSRgvEejh6VXGQYymv5h3chEOVbLq3mnWyNd1lbg==</dsig:SignatureValue><dsig:KeyInfo><dsig:KeyValue><dsig:RSAKeyValue><dsig:Modulus>0Q2QN4cCxc10Azb7CC4uas7efiPZOwwUHykxLIfHtc8Oxw2PkoBrSeMyA/skCewDvMJZHmc2SOdnA6DpqZ6rlXe7R6yzM4ytHIg4ijE4+PYotiP0lUTTTgIf3mbvaAiLUTZV1sz4TjmcSk95v4mb4CsqaDMGE+2EPyp0DW0NBqaynaE4aVKuGOxJAosJBBZodAOlthpMU59hL7JqBXQJKNvQsyxnJYHgJnLWaGUn8D8+Y1MMJgVjSrmtxqv/2coVaSJrRqSYirn+GmYgRGRR/BUyIikUROyGLo5Y/LtUvuTQM1vetHkcd3LJP7MpWqG9PDzvx412FbPw0sISzCLgaQ==</dsig:Modulus><dsig:Exponent>AQAB</dsig:Exponent></dsig:RSAKeyValue></dsig:KeyValue></dsig:KeyInfo></dsig:Signature><samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/><samlp:RequestedAuthnContext Comparison="minimum"><saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef></samlp:RequestedAuthnContext></samlp:AuthnRequest>`

**Comment by stefanorg** [comment]
@marcoz-tsn anche io vorrei integrare keycloak come identity broker, hai qualche risorsa da consigliare, qualche repository di esempio che posso seguire?

**Comment by marcoz-tsn** [comment]
@stefanorg se non hai ancora sperimentato keycloak puoi avviare una versione dockerizzata, ne trovi in https://github.com/jboss-dockerfiles/keycloak, ma io mi sono trovato meglio con https://github.com/eugen/docker-keycloak
Purtroppo ho scoperto successivamente che la versione "vanilla" non si integra con SPID, sia a causa di alcune mancanze di keycloak, sia per deroghe allo standard SAML2 presenti in SPID.

La mia soluzione è stata effettuare il fork del progetto (v. 4.6.0), seguire il README in https://github.com/keycloak/keycloak per il build e run e implementare nel codice le modifiche di compatilibilità con SPID.
HTH

**Comment by stefanorg** [comment]
ciao @marcoz-tsn, si anche io sto utilizzando docker e ho creato uno UserStorageProvider custom, ho notato anche io le difficoltà con SPID per via delle "deroghe" mi piacebbe vedere le modifiche che hai effettuato per poterle riportare in un mio fork del progetto, il repo dove hai fatto queste modifiche è pubblico? mi puoi dare il link?

Grazie mille

**Comment by publicocean0** [comment]
mi pare ora il problema con salm nn ci sia piu' perche' si passa a oauth?

**Comment by stefanorg** [comment]
Ma c'è qualche implementazione di spid-oidc già da poter provare o ancora è
tutto in bozza?

Il dom 14 giu 2020, 11:27 publicocean0 <notifications@github.com> ha
scritto:
