### ISSUE TITLE
RequestedAttributes di Spid non riconosciuti

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-testenv2#144]
Se richiedo i campi

`fiscalNumber`, `digitalAddress`, `placeOfBirth`, `ivaCode`, `idCard`, `mobilePhone`, `digitalAddress`, `address`

ricevo un errore come se avessi inserito attributi non esistenti, ma i valori sono presenti in 

https://github.com/italia/spid-testenv2/blob/652becab9f946b343ba96cd9e8278a67f08a0d95/testenv/settings.py#L17-L39

![screenshot from 2018-08-27 14-40-00](https://user-images.githubusercontent.com/400256/44660215-442b9500-aa07-11e8-80ca-05a8d313c517.png)

```
127.0.0.1 - - [27/Aug/2018 14:43:51] "GET /sso?SAMLRequest=nVLLasMwEPwV33Tys47tijgQEgqBtLRJ6aGXothyIrAkV7vO4%2B8rOw8CbVPoTezO7s6MZghM1g0dt7hRC%2F7ZckBnDMANCq0mWkEruVlysxUFn6mS73MSEGeMaMSqRX5ECLX%2BBpnaTUKxbk1ONogN9X1RNl693XiS0yzIMh9AE2c2zclHnLBqkBSpy8r7wI3jInJXVblyw6RM0iRlURyFFgrQ2hOATGFOoiDM3CBzo%2FQ1jGh8RwfhO3HeuIH%2BZuRZFntZK6Cdxpy0RlHNQABVTHKgWNDl%2BHFOLZCys%2BTrkeb2TGM06kLXZDTs0LRnZ5wHbSTD26NdRZRu1UMpVyjwQJwnW31pWS0qwc3FNGgsEjorDTu7Fw%2BSlIz%2BAAz9K1pHjg3tbsymz7oWxeEfVO0JBcISJv554yk1vOwzZAOBfI%2FORMuGGQHdT9h8CNnKs0%2FXuEltnV%2FwqtcCVsxut%2FM6Qd5abz2B%2FtK%2B5%2BFJyo%2BTx94vPC7d64CPvgA%3D&RelayState=%2F&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=0xokKSdlKrk%2BVl1zbNWKM9%2Frudi5fNfUX2fKJjvMlzXS4unJjHLbUCV6klVj%0AqLSHGhzM4Rrg1%2BpAJgVmc%2F2WRSHDaXEDXyxaQSxGtqX0oB3ouQ927Xepem7i%0Ayjngcv5hboWtD0rvqeI2ZAgtKiGplHcrw4D7CzGDEITPt3FoCIm1Jwgj%2FeAk%0ANicyNzY06KajU9%2Fs0TD8SGCivDBS6g4iW36zbydx0Q%2BwS%2BWqKpbUwfYG%2BYb3%0AQbdC7%2Bgtblv%2B1qUC84GMVdzU83vx8B6VltGyML%2BDaurOqDayS7ck4vsLv0TW%0AaHNn5ybN%2Fyhzo9Ud2Tq1%2BaGQ14TbKobpeqbev%2FC2FFWq33sRlhSIPr3UzG27%0A6VxVKHbG50EKx3egTdFa9amplSRCmt2AMGnNmlubntHLgPDtktqncBgbfpij%0A0G7Xyldj5I%2FC9UKAylPfya%2BKYXHafTb3XLyBm1jqKUE%2BkgCl2VNu%2B8DAaZzf%0ApbcRLM1XIl%2FkudikSqnh1tS5Bm6ZAiLHnrjNxaWB34yB5qY7ExMRiXkOTDsf%0AkMl6Aec5TMo85LHIMP2ADxs529Y%2FdCocVu2mQ6747TZk9oHTFoEXM9dFc51S%0AOpGftnHPoPVlZ8Hd%2BbKVI9NCS%2FCQ9bCkl7A0GiRnhtxrZ9ec6ITxSEYDgO9P%0A0KB8FRjCnVRiMplketuc63Q%3D%0A HTTP/1.1" 302 -
[2018-08-27 14:43:51,789] DEBUG in server: Request key: d7aac182300b38d0b6d581ca19613ab4a54ff888
[2018-08-27 14:43:51,790] DEBUG in server: AssertionConsumerServiceIndex Location: http://spid-sinatra.lvh.me:4567/spid/sso
[2018-08-27 14:43:51,790] DEBUG in server: spid level 0 - verifica (False)
127.0.0.1 - - [27/Aug/2018 14:43:51] "GET /login HTTP/1.1" 200 -
[2018-08-27 14:43:52,580] DEBUG in server: Request key: d7aac182300b38d0b6d581ca19613ab4a54ff888
[2018-08-27 14:43:52,580] DEBUG in server: AssertionConsumerServiceIndex Location: http://spid-sinatra.lvh.me:4567/spid/sso
[2018-08-27 14:43:52,581] DEBUG in server: spid level 0 - verifica (True)
[2018-08-27 14:43:52,581] DEBUG in server: Unfiltered data: {u'name': u'Zaccaria', u'companyName': u'Mazza, Silvestri e Costa SPA', u'gender': u'F', u'familyName': u"D'amico", u'email': u'nadirbruno@yahoo.com', u'registeredOffice': u'Strada Battista 6\nNabil del friuli, 26915 Trento (PV)', u'dateOfBirth': u'1982-05-03', u'spidCode': u'c47ac554-4af1-1db3-a440-1678324b9d48'}
[2018-08-27 14:43:52,581] DEBUG in server: AttributeConsumingServiceIndex: 0
127.0.0.1 - - [27/Aug/2018 14:43:52] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dalzhe/Projects/Cantiere/DevelopersItalia/spid-testenv2/testenv/server.py", line 569, in login
    _identity[_key] = identity[_key]
KeyError: 'idCard'
127.0.0.1 - - [27/Aug/2018 14:43:52] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2018 14:43:52] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2018 14:43:52] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2018 14:43:52] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by davidlibrera** [comment]
#164 Lo riporto anche qui

**Comment by fmarco** [comment]
@davidlibrera pushato fix su master

**Comment by fmarco** [comment]
@davidlibrera Ciao, si può chiudere questa?
