### ISSUE TITLE
Supportare dichiarazioni XML nei messaggi SAML

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#146]
Dopo i recenti commit, e usando l'immagine docker più aggiornata, ricevo questo errore quando dal SP (nel mio caso il progetto spid-dotnet-sdk) seleziono nella tendina degli IdP SPID quello corrispondente a spid-testenv2:

```
builtins.ValueError
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Traceback (most recent call last)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/testenv/server.py", line 378, in single_sign_on_service
spid_request = self._parse_message(action='login')
File "/app/testenv/server.py", line 323, in _parse_message
return self._handle_http_post(action)
File "/app/testenv/server.py", line 356, in _handle_http_post
saml_tree = deserializer.deserialize()
File "/app/testenv/parser.py", line 188, in deserialize
self._validate()
File "/app/testenv/parser.py", line 198, in _validate
self._run_validators()
File "/app/testenv/parser.py", line 204, in _run_validators
self._run_validator(validator)
File "/app/testenv/parser.py", line 208, in _run_validator
validator.validate(self._request)
File "/app/testenv/validators.py", line 39, in validate
etree.fromstring(request.saml_request, parser=self._parser)
File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
 
File "src/lxml/parser.pxi", line 1872, in lxml.etree._parseMemoryDocument
 
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by alexrj** [comment]
Io non riesco a riprodurre questo problema.

**Comment by marcoz-tsn** [comment]
Si verifica se la dichiarazione XML della richiesta SAML passata nel campo SAMLRequest contiene l'attributo `encoding`.
Nel mio caso è bastato togliere `encoding="UTF-8"` dall'output del metodo BuildAuthnPostRequest della classe SamlHelper del progetto **spid-dotnet-sdk**.
Tuttavia non dovrebbe essere necessario, IMHO.

**Comment by alexrj** [comment]
@marcoz-tsn quindi la tua AuthnRequest è preceduta dalla dichiarazione:
`<?xml version=“1.0” encoding=“utf-8”?>` ?

**Comment by alexrj** [comment]
Ok sì, si vede da qui: https://github.com/italia/spid-dotnet-sdk/blob/5692c9f5d19b81723e73042fdc6ae0453550083e/Italia.Spid.Authentication/Saml/SamlHelper.cs#L143

**Comment by alexrj** [comment]
Quindi questa issue diventa: dobbiamo supportare la presenza di eventuali dichiarazioni XML all'inizio dei messaggi SAML.

**Comment by marcoz-tsn** [comment]
Confermo risoluzione della casistica, grazie.
