### ISSUE TITLE
Messaggi più chiari per validazione configurazione

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#16]
Bisogna fare in modo che la validazione del file di configurazione produca messaggi semplici e comprensibili. Ad esempio mi esce questo e non mi fa capire dove intervenire:

```
$ python spid-testenv.py
Traceback (most recent call last):
  File "spid-testenv.py", line 671, in <module>
    server = IdpServer(app=Flask(__name__), config=config)
  File "spid-testenv.py", line 208, in __init__
    self._prepare_server()
  File "spid-testenv.py", line 300, in _prepare_server
    self._setup_app_routes()
  File "spid-testenv.py", line 282, in _setup_app_routes
    self.app.add_url_rule(_url, '{}_{}'.format(ep_type, _binding), getattr(self, ep_type), methods=['GET',])
  File "/home/staff/spid-testenv2/env/local/lib/python2.7/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/staff/spid-testenv2/env/local/lib/python2.7/site-packages/flask/app.py", line 1043, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/home/staff/spid-testenv2/env/local/lib/python2.7/site-packages/werkzeug/routing.py", line 603, in __init__
    raise ValueError('urls must start with a leading slash')
ValueError: urls must start with a leading slash
```

**Comment by fmarco** [comment]
@alexrj questa si può chiudere?
