### ISSUE TITLE
Problemi installazione requirements su OSX

### ISSUE THREAD

**Issue by spleenteo** [italia/spid-testenv2#173]
Ciao
premesso: sono assolutamente a digiuno di python.

Su un ambiente osx, ho python installato via brew e sembra funzionare tutto. Ho seguito il readme e installato tutte le dipendenze. pip3 funziona bene e il virtualenv mi crea l'ambiente correttamente

     $ python --version
     $ Python 2.7.10
     
     $ which python
     $ /Users/matteo/Sites/spid-testenv2/env/bin/python

Quando vado ad installare i requirements però ottengo un errore

    $ pip install -r requirements.txt

    $ Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-install-Dg1Qka/importlib-resources/

L'output completo

````
Looking in indexes: https://pypi.org/simple, https://devpi.iast.it/nephila/dev/+simple
Collecting asn1crypto==0.24.0 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting certifi==2018.8.24 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting cffi==1.11.5 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/7e/4a/b647e46faaa2dcfb16069b6aad2d8509982fd63710a325b8ad7db80f18be/cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl
Collecting chardet==3.0.4 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting cryptography==2.3.1 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/5d/b1/9863611b121ee524135bc0068533e6d238cc837337170e722224fe940e2d/cryptography-2.3.1-cp27-cp27m-macosx_10_6_intel.whl
Collecting defusedxml==0.5.0 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting eight==0.4.2 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/4a/93/ef92a6f172eaf8c35377f8ce96eaf2e59032af70ed1f044b65609c65c6f9/eight-0.4.2-py2.py3-none-any.whl
Collecting exrex==0.10.5 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/68/5a/1f0940e6bc490825bab1d3e9441cd90f6a27d1c6022db1b12772f38de04b/exrex-0.10.5.tar.gz
Collecting faker==0.8.16 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/e3/d8/e4967bdae2961bb4ab8e23ace6fcef74312fdefae591a46424b8568e16ee/Faker-0.8.16-py2.py3-none-any.whl
Collecting flask==1.0.2 (from -r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting idna==2.7 (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting importlib-resources==1.0.1 (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/d2/09/1f4148ee5ec0022d122bb9a94428a70f858863d47df573dd8c382fa8f1c2/importlib_resources-1.0.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/typing/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'typing' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for typing; python_version < "3.5"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-install-Dg1Qka/importlib-resources/setup.py", line 2, in <module>
        setup()
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in setup
        _install_setup_requires(attrs)
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/setuptools/__init__.py", line 134, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
        replace_conflicting=replace_conflicting
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
        return self.obtain(req, installer)
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
        return installer(requirement)
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-build-env-dKBfkZ/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('typing; python_version < "3.5"')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/br/ycnl49zj7q784h_zpvrnd5rr0000gn/T/pip-install-Dg1Qka/importlib-resources/
````

**Comment by bfabio** [comment]
@spleenteo Does it work with the latest version?

**Comment by peppelinux** [comment]
please try the latest version :)
