### ISSUE TITLE
Errore in spmetadata.py se l'attributo ID del nodo EntityDescription contiene un GUID che inizia con una cifra

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#184]
Per esempio se il GUID è: **37103390-6301-4e88-90b7-6dc549b81537** e controllo i logs, trovo:
```
Traceback (most recent call last):
  File "/app/testenv/spmetadata.py", line 44, in _validate
    self._validator.validate(metadata)
  File "/app/testenv/validators.py", line 39, in validate
    raise GroupValidationError(self._validation_errors)
testenv.exceptions.GroupValidationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spid-testenv.py", line 30, in <module>
    spmetadata.build_metadata_registry()
  File "/app/testenv/spmetadata.py", line 260, in build_metadata_registry
    _populate_registry(registry)
  File "/app/testenv/spmetadata.py", line 268, in _populate_registry
    registry.register(metadata)
  File "/app/testenv/spmetadata.py", line 234, in register
    self._register(metadata)
  File "/app/testenv/spmetadata.py", line 240, in _register
    entity_id = metadata.entity_id
  File "/app/testenv/spmetadata.py", line 100, in entity_id
    return self.root.get(
  File "/app/testenv/spmetadata.py", line 94, in root
    return self._metadata.get(
  File "/app/testenv/spmetadata.py", line 223, in _metadata
    metadata = self._loader.load()
  File "/app/testenv/spmetadata.py", line 39, in load
    self._validate(metadata)
  File "/app/testenv/spmetadata.py", line 46, in _validate
    raise DeserializationError(metadata, e.details)
testenv.exceptions.DeserializationError
Traceback (most recent call last):
  File "/app/testenv/spmetadata.py", line 44, in _validate
    self._validator.validate(metadata)
  File "/app/testenv/validators.py", line 39, in validate
    raise GroupValidationError(self._validation_errors)
testenv.exceptions.GroupValidationError
```
Sostituendo il GUID per esempio con **d5d8f180-f0b4-4ae6-b977-b30a945f0fe5**, torna a funzionare.

**Comment by alexrj** [comment]
Questo è incluso in #38. Lo riporto lì e chiudo questa. Grazie!
