### ISSUE TITLE
LogoutRequest: errore builtins.KeyError

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#186]
Questa regression impedisce l'accettazione di un messaggio LogoutRequest.

```xml
<saml2p:LogoutRequest ID="_cc66a5f04ab7fe1ba1ad529931264197" Version="2.0" Destination="http://localhost:8088" IssueInstant="2018-09-20T08:48:37Z" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://www.prova.it/">https://www.prova.it/</saml2:Issuer><saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" NameQualifier="http://localhost:8088">id_0a01256bf9fd114109298c7dad9eb755e66bfe29</saml2:NameID><saml2p:SessionIndex>id_c47caab805a071e1834a041c059c92e03b23d13f</saml2p:SessionIndex></saml2p:LogoutRequest>
```

Errore:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/testenv/server.py", line 695, in single_logout_service
    response_binding = _slo[0].get('Binding')
KeyError: 0
```

Estratto dai metadati SP:

```
        <md:SingleLogoutService 
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
            Location="http://localhost:3000/spid-slo" /> 
```

**Comment by fmarco** [comment]
@alexrj mergiato
