### ISSUE TITLE
[Python3.8] ImportError: cannot import name 'Feature' from 'setuptools' 

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-testenv2#305]
Per chi tentasse di installare spid-testenv2 in un virtualenv costruito al di sopra di python3.8 e ottenesse il seguente errore
````
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3gk1vitu/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/home/wert/DEV/DTD/Spid/env/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
````

Soluzione
-------------
````
pip3 install setuptools==45
````

**Comment by peppelinux** [comment]
Per l'eccezione 
````
TypeError: required field "type_ignores" missing from Module
````

risolvere installando `pip install werkzeug==0.15.5`

**Comment by peppelinux** [comment]
Il branch master attualmente funziona con Python versione 38, tuttavia questa è da integrare in CI
