### ISSUE TITLE
Validazione configurazione

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#39]
La mancata validazione del file di configurazione del testenv deve generare errori comprensibili.

Ad esempio, se avvio il testenv senza aver configurato nessun metadata SP ottengo questo errore poco comprensibile:

```
Traceback (most recent call last):
  File "spid-testenv.py", line 708, in <module>
    server = IdpServer(app=Flask(__name__), config=config)
  File "spid-testenv.py", line 224, in __init__
    self._prepare_server()
  File "spid-testenv.py", line 341, in _prepare_server
    self.idp_config.load(cnf=self._idp_config())
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/config.py", line 356, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/config.py", line 296, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/config.py", line 400, in load_metadata
    mds.imp(metadata_conf)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/mdstore.py", line 918, in imp
    for val in vals:
TypeError: 'NoneType' object is not iterable
```

**Comment by alexrj** [comment]
Per essere preciso, questo output usciva con questa configurazione:

```yaml
metadata:
  local:
#  - "sp_metadata.xml"
  remote:
#  - url: "http://spid-sp/metadata
#    cert: "spid-sp.cert"
```

**Comment by fmarco** [comment]
@alexrj ho pushato un fix per questa cosa (pysaml2 considerava le due liste come settate a None e per quello restituiva errore)
