### ISSUE TITLE
Errore dopo l'invio delle credenziali

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#54]
Sto testando il branch `feature/issue-3-validazione-login`.

Dopo aver inserito le credenziali dell'utente nella schermata di login, ottengo questo errore:

```
127.0.0.1 - - [07/Jul/2018 12:04:09] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 998, in login
    'lines':  escape(prettify_xml(response)).splitlines(),
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 206, in prettify_xml
    msg = etree.tostring(etree.XML(msg), pretty_print=True)
  File "src/lxml/etree.pyx", line 3192, in lxml.etree.XML

  File "src/lxml/parser.pxi", line 1872, in lxml.etree._parseMemoryDocument

ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by fmarco** [comment]
@alexrj ps: con l'ultima PR mergiata il problema non dovrebbe presentarsi, fai pure un test con master aggiornato.

**Comment by fmarco** [comment]
@alexrj D'accordo, allora indago basandomi sul tuo messaggio, grazie :+1:

**Comment by fmarco** [comment]
@alexrj potresti riprovare nuovamente con master aggiornato? (era un problema dovuto alle differenti versioni di python riguardo alla gestione delle stringhe)

**Comment by alexrj** [comment]
Testato ora, funziona.
