### ISSUE TITLE
AuthnRequest: UnsupportedBinding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#70]
Se invio la seguente AuthnRequest:

```xml
<saml2p:AuthnRequest IssueInstant="2018-07-15T22:35:31Z" ForceAuthn="false" ID="3fa49d3d26a16bb7eedd4c67bff68479" Destination="http://localhost:8088/sso" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:AuthnRequest>
```

ottengo il seguente errore:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 972, in single_sign_on_service
    acss = self.server.metadata.assertion_consumer_service(sp_id, authn_req.protocol_binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/mdstore.py", line 1101, in assertion_consumer_service
    "assertion_consumer_service", binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python2.7/site-packages/saml2/mdstore.py", line 988, in service
    raise UnsupportedBinding(binding)
UnsupportedBinding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
```

**Comment by fmarco** [comment]
@alexrj ho pushato un fix su master

**Comment by fmarco** [comment]
@alexrj issue testata in #78

**Comment by alexrj** [comment]
@fmarco purtroppo ancora non mi accetta il valore.

Inviando via GET questa AuthnRequest:

```xml
<saml2p:AuthnRequest IssueInstant="2018-07-19T11:13:26Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" ForceAuthn="false" ID="b50f9e10b74ef94b4db72aa54961d89b" Destination="http://localhost:8088/sso" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:AuthnRequest>
```

ottengo questa schermata:

![screen shot 2018-07-19 at 13 15 23](https://user-images.githubusercontent.com/594957/42939408-d43ee17c-8b55-11e8-8817-b4426269df2f.png)

**Comment by alexrj** [comment]
Hai ragione. Ho fatto confusione io. `ProtocolBinding`, se presente, deve essere sempre validato con HTTP-POST.
