### ISSUE TITLE
AuthnRequest: jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#71]
Inviando la seguente AuthnRequest:

```xml
<saml2p:AuthnRequest Version="2.0" Destination="http://localhost:8088/sso" ForceAuthn="false" ID="d00944814ad068126f000fa1f42243e9" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" IssueInstant="2018-07-15T22:52:52Z" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:AuthnRequest>
```

ottengo il seguente errore:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 982, in single_sign_on_service
    return self._handle_errors(errors, req_info.xmlstr)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 940, in _handle_errors
    'errors': errors
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template_string
    context, ctx.app)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 28, in top-level template code

jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
```

Python 3.7.0

**Comment by fmarco** [comment]
@alexrj ho aggiornato master con un fix
