### ISSUE TITLE
AuthnRequest: IndexError: list index out of range

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#72]
con questo AuthnRequest:
```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_5c4d8dd61331d422140ff185cc1a9f3efbb629a5"
                    Version="2.0"
                    IssueInstant="2018-07-16T05:42:29Z"
                    Destination="http://idp.simevo.com:8088/sso"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="http://sp2.simevo.com:8000/index.php?acs">
  <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
               NameQualifier="http://sp2.simevo.com:8000">http://sp2.simevo.com:8000/metadata.php</saml:Issuer>
  <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
  <samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
ottengo:
```
192.168.122.1 - - [16/Jul/2018 05:42:29] "GET /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/testenv2/spid-testenv.py", line 1109, in login
    spid_level = authn_request.message.requested_authn_context.authn_context_class_ref[0].text
IndexError: list index out of range
```

**Comment by fmarco** [comment]
@simevo non riesco a riprodurre l'errore (nè su py3 nè su py2). Stai usando master aggiornato?

**Comment by simevo** [comment]
sorry my fault

**Comment by alexrj** [comment]
@simevo puoi condividere qui cosa sbagliavi?
