### ISSUE TITLE
saml2.response.IncorrectlySigned

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#76]
sto effettuando il logout e mi risponde con `saml2.response.IncorrectlySigned`:
```
[2018-07-16 18:43:45,286] DEBUG in spid-testenv: req: '<Request 'http://idp.simevo.com:8088/slo?SAMLRequest=nZJLb9swEITv%2BRWG7rZI60URtoACbg0BjoMkRQ%2B9FMtXQ0AiFS0VJPn1kSW3cAI0h%2FI43G9mFuQGoW06fvC%2F%2FRDu9OOgMVwtxvPcNg75dLuNht5xD2iRO2g18iD5%2FZfrA1%2BvCO96H7z0TfQB%2B5wCRN0H692M1bttdHP8erjZ18dfALnQUiglCRHFOmEJycGwkjGQudFKSshIWiYz%2BkP3OPpso9H2bIY46NphABdGmVC2JMWS5t9pztOEp9nPeW437modhIl%2BCKHjcWxVt0Lb6ie%2Fkr7ljDAWY%2BOjaiI2p8X45N8vvvm%2BhfD5mifFqqWZRrl2wYaXaHEc1dsBGmus7v9GY7d%2BH01IVP37Lm51AAUBVt1Dt4kvml12PUXVu%2F%2FoGnpwaMfGUaWLlJVSCpJmQuYZLXPBWEmzlFFRsEwIQwhLMqVBSKZMSZUyay2ohJTkRhTncnOVi3Idv9d4ervaKf1cjdkHOoRE7l4Lc1skar%2BvZ%2FTD4NUf9d2vrd4A&RelayState=http%3A%2F%2Fsp2.simevo.com%3A8000%2F&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=Cl0WilrDA3TSOw2e5zugAEcCLwZn1lWfIMnLHEs5t6TZIcbpk2FDX3anXfVp0l6wWQsDn%2Br%2FImU87MuPjNgwUvdu7YhYoWgJTBYhO3qqW20HuOEd6IRNdXXFfli1uirwEN7iztZYGCkEyXZQtcy%2F7TUpmvcBIIs1HgTEHRqE5wkdRhCqsuf7u%2F04eNi5h%2Fdjk%2FgDIhbEGOnFX7FbhRF5vmnPz9iFttrEu8qn4pytMtgaDb%2BLMz31MEw%2BBBVSt4qJNCE8zs416Q8NqQcaivvKXUNtJPH98uBmLSPGCFNploM%2F619bFShCHptYqq2dwfAxptDxHKAUQV2xOSr%2FraaiGQ%3D%3D' [GET]>'
192.168.122.1 - - [16/Jul/2018 18:43:45] "GET /slo?SAMLRequest=nZJLb9swEITv%2BRWG7rZI60URtoACbg0BjoMkRQ%2B9FMtXQ0AiFS0VJPn1kSW3cAI0h%2FI43G9mFuQGoW06fvC%2F%2FRDu9OOgMVwtxvPcNg75dLuNht5xD2iRO2g18iD5%2FZfrA1%2BvCO96H7z0TfQB%2B5wCRN0H692M1bttdHP8erjZ18dfALnQUiglCRHFOmEJycGwkjGQudFKSshIWiYz%2BkP3OPpso9H2bIY46NphABdGmVC2JMWS5t9pztOEp9nPeW437modhIl%2BCKHjcWxVt0Lb6ie%2Fkr7ljDAWY%2BOjaiI2p8X45N8vvvm%2BhfD5mifFqqWZRrl2wYaXaHEc1dsBGmus7v9GY7d%2BH01IVP37Lm51AAUBVt1Dt4kvml12PUXVu%2F%2FoGnpwaMfGUaWLlJVSCpJmQuYZLXPBWEmzlFFRsEwIQwhLMqVBSKZMSZUyay2ohJTkRhTncnOVi3Idv9d4ervaKf1cjdkHOoRE7l4Lc1skar%2BvZ%2FTD4NUf9d2vrd4A&RelayState=http%3A%2F%2Fsp2.simevo.com%3A8000%2F&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=Cl0WilrDA3TSOw2e5zugAEcCLwZn1lWfIMnLHEs5t6TZIcbpk2FDX3anXfVp0l6wWQsDn%2Br%2FImU87MuPjNgwUvdu7YhYoWgJTBYhO3qqW20HuOEd6IRNdXXFfli1uirwEN7iztZYGCkEyXZQtcy%2F7TUpmvcBIIs1HgTEHRqE5wkdRhCqsuf7u%2F04eNi5h%2Fdjk%2FgDIhbEGOnFX7FbhRF5vmnPz9iFttrEu8qn4pytMtgaDb%2BLMz31MEw%2BBBVSt4qJNCE8zs416Q8NqQcaivvKXUNtJPH98uBmLSPGCFNploM%2F619bFShCHptYqq2dwfAxptDxHKAUQV2xOSr%2FraaiGQ%3D%3D HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/testenv2/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/testenv2/spid-testenv.py", line 1294, in single_logout_service
    req_info = self.server.parse_logout_request(saml_msg['SAMLRequest'], _binding)
  File "/srv/testenv2/env/lib/python2.7/site-packages/saml2/entity.py", line 1198, in parse_logout_request
    "single_logout_service", binding)
  File "/srv/testenv2/env/lib/python2.7/site-packages/saml2/entity.py", line 852, in _parse_request
    must=must, only_valid_cert=only_valid_cert)
  File "/srv/testenv2/env/lib/python2.7/site-packages/saml2/request.py", line 96, in loads
    only_valid_cert=only_valid_cert)
  File "/srv/testenv2/env/lib/python2.7/site-packages/saml2/request.py", line 59, in _loads
    raise IncorrectlySigned()
IncorrectlySigned
```
tra l'altro dice `saml_msg['SAMLRequest']` quindi è la request o la response che non sarebbe firmata  ?

e cmq l'SP è configurato per firmare tutto e secondo l'estensione chrome SAML Message Decoder la request è firmata:
![screenshot_20180716_183624](https://user-images.githubusercontent.com/8254819/42771599-0c54b418-8928-11e8-82f9-948de92c5d3a.png)

**Comment by fmarco** [comment]
@simevo pushato fix su master

**Comment by simevo** [comment]
risolto per me, grazie
