### ISSUE TITLE
Errore UnicodeDecodeError in XML Response

### ISSUE THREAD

**Issue by lorenzocattaneo** [italia/spid-testenv2#83]
Inviando la seguente Request:

```xml
<samlp:AuthnRequest AssertionConsumerServiceURL="http://sp2.simevo.com/index.php?acs"
    Destination="http://idp.simevo.com:8088/sso" ID="ONELOGIN_547c686eef18445e111e749e0f52c4c84c0072ee"
    IssueInstant="2018-07-21T12:41:19Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
        NameQualifier="http://sp2.simevo.com:8000">http://sp2.simevo.com/metadata.php</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

Ottengo questo errore:

<img width="1663" alt="schermata 2018-07-19 alle 16 32 19" src="https://user-images.githubusercontent.com/22037356/43036090-cdeea3f6-8cfa-11e8-8158-4989d84f4362.png">

E osservando i log di debug vedo:

[2018-07-21 15:13:06,190] DEBUG in spid-testenv: spid level 1 - verifica (True)
[2018-07-21 15:13:06,224] DEBUG in spid-testenv: Response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="http://sp2.simevo.com:8000/index.php?acs" ID="id-5iUK294ScfzWe4OdL" InResponseTo="ONELOGIN_59cf261e287c157f7ab04883684820cdee82d551" IssueInstant="2018-07-21T13:13:06Z" Version="2.0">
	<Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
		http://idp.simevo.com:8088
	</Issuer>
	<Status>
		<StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
	</Status>
	<Assertion ID="id-YVzIltmHVtIUHgMy0" IssueInstant="2018-07-21T13:13:06Z" Version="2.0">
		<Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
			http://idp.simevo.com:8088
		</Issuer>
		<Signature Id="Signature2">
			<SignedInfo>
				<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512" />
				<Reference URI="#id-YVzIltmHVtIUHgMy0">
					<Transforms>
						<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
						<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					</Transforms>
					<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512" />
					<DigestValue>
						IyuAbQ2ATYeBZZgk/+oTFumLajLZBa5MnmzM8q0x7Zo7ZPVXmDFCoE1GtZzxvPi0
						vCdyvyoaUlLqb6QOIfRf7w==
					</DigestValue>
				</Reference>
			</SignedInfo>
			<SignatureValue>
				OGIjmLVh4vevrh9Q+5z83T2epm/fs2pCZekzHH40ea0F+P97kCzmz+HwMafdTnSs
				hsqIxCc5mneZt07r+jAQr0gqxk+GOIunC+W2m1STCMLNQzGJRomcyKfLgdYFARQZ
				kbUAYufibTGkOvli9sY5tee718964GmWxrnDQV6W7jXsxabtZ1OXx4qL69VYVPaG
				h64vuJ///vms1dNMYuTVMr17QA1CdJKoJET3WEj8v0fJpJC6KdDaQuvcpdZ+UXEt
				sXya10IKJ6M5X7OSyIMz3i5d+VK5YZ2rK0qD/uZJusqdy9awxXJbGMBBclTF/1GV
				FQq+X1Z6uDFwQfGRouyeNw==
			</SignatureValue>
			<KeyInfo>
				<X509Data>
					<X509Certificate>
						MIIDiDCCAnCgAwIBAgIJAJnqANY7GvtNMA0GCSqGSIb3DQEBCwUAMFkxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTERMA8GA1UECgwIdGVzdGVudjIxGDAWBgNVBAMMDyR7YW5zaWJsZV9mcWRufTAeFw0xODA3MTkxMzEwMDVaFw0xOTA3MTkxMzEwMDVaMFkxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTERMA8GA1UECgwIdGVzdGVudjIxGDAWBgNVBAMMDyR7YW5zaWJsZV9mcWRufTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALTPycItk7xvubL0WgegvbtCvhzeCq13WorzjYQdpWvUwY8YmL51h6ssKfWMfnSj96IxlJw2HTm+TgHK2/S7Iw7gh6xoaY+LDmkZGJKzUSFR/Hn7WbFNb3jytowiNDQdcBZdhNhEnDvd2fLMGxD81qdlMx3y5XHP+p9Gc8bjp8aShGw+DQpWBXcfoDnCXz5ywmnRoD66CnMFMQXmD0wZf79/0fY+Muwn83r7P0h6bJCFDjPdGiSeo7q5AJKkERoNoedcHThCuT0uN36bDaVBIcSxVtPjvVhfcNIVN5JHaCLZT89aU8DAJlTUiO3u5Nj4aDjDXAhxMWkwGbHXCznhjVMCAwEAAaNTMFEwHQYDVR0OBBYEFH1/ReU+04oYtVpMgD/zVCPuagu6MB8GA1UdIwQYMBaAFH1/ReU+04oYtVpMgD/zVCPuagu6MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAAWT9+r+ojVmxUUZvq8/TumEX9Y0FxxQebTcPMeumA58mp9kDCeNK73PZ6cbQSGXzwbNmHw48N2kZMl3rS8ddYPG3nFxEZO5Xi0De2SLGwLZX43lfD4BHhhqhTlnBK8cL+LvySQ32X1vL8aKly/UTez3/DCrdTqFjp1V0PdY2q0Ni3UAiO90MpFGbP+aAQ1LGtI0EWpDCVAqqgAA2EA+s0AlwbC5cuDbQUjHA5dhkWT/4kvHB/E5zPZUtRV4d3mYBs33lfIyKXWjjgR4T8j01wMk2LWCnBU8i4mCb1w3v94KcRbnK23bJLz+zNp6I3belhLknSahyjKPl+6FBSyW/GE=
					</X509Certificate>
				</X509Data>
			</KeyInfo>
		</Signature>
		<Subject>
			<NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" NameQualifier="http://idp.simevo.com:8088" SPNameQualifier="http://sp2.simevo.com:8000/metadata.php">
				a49d0ad1a26fc392c4a079e49e9e921598c75cd6e817c5ccbbc025efacf2f948
			</NameID>
			<SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<SubjectConfirmationData InResponseTo="ONELOGIN_59cf261e287c157f7ab04883684820cdee82d551" NotOnOrAfter="2018-07-21T14:13:06Z" Recipient="http://sp2.simevo.com:8000/index.php?acs" />
			</SubjectConfirmation>
		</Subject>
		<Conditions NotBefore="2018-07-21T13:13:06Z" NotOnOrAfter="2018-07-21T14:13:06Z">
			<AudienceRestriction>
				<Audience>
					http://sp2.simevo.com:8000/metadata.php
				</Audience>
			</AudienceRestriction>
		</Conditions>
		<AuthnStatement AuthnInstant="2018-07-21T13:13:06Z" SessionIndex="id-xlpneRaI7RugChANX">
			<AuthnContext>
				<AuthnContextClassRef>
					https://www.spid.gov.it/SpidL1
				</AuthnContextClassRef>
				<AuthenticatingAuthority>
					https://www.spid.gov.it/SpidL1
				</AuthenticatingAuthority>
			</AuthnContext>
		</AuthnStatement>
		<AttributeStatement>
			<Attribute FriendlyName="name" Name="urn:mace:dir:attribute-def:name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Moreno
				</AttributeValue>
			</Attribute>
			<Attribute Name="companyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Moretti-Ricci s.r.l.
				</AttributeValue>
			</Attribute>
			<Attribute Name="gender" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					M
				</AttributeValue>
			</Attribute>
			<Attribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Piras
				</AttributeValue>
			</Attribute>
			<Attribute Name="birthDate" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					1975-04-21
				</AttributeValue>
			</Attribute>
			<Attribute Name="registeredOffice" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Stretto Ferrara 871 Appartamento 85
					Settimo Emanuel, 71694 Forlì-Cesena (FM)
				</AttributeValue>
			</Attribute>
			<Attribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					e6edd069-345c-9ec0-9655-d75365260ba0
				</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="email" Name="urn:mace:dir:attribute-def:email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					gabrielefontana@vitale.org
				</AttributeValue>
			</Attribute>
		</AttributeStatement>
	</Assertion>
</Response>
<?xml version="1.0" encoding="UTF-8"?>
<Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="http://sp2.simevo.com:8000/index.php?acs" ID="id-5iUK294ScfzWe4OdL" InResponseTo="ONELOGIN_59cf261e287c157f7ab04883684820cdee82d551" IssueInstant="2018-07-21T13:13:06Z" Version="2.0">
	<Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
		http://idp.simevo.com:8088
	</Issuer>
	<Status>
		<StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
	</Status>
	<Assertion ID="id-YVzIltmHVtIUHgMy0" IssueInstant="2018-07-21T13:13:06Z" Version="2.0">
		<Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
			http://idp.simevo.com:8088
		</Issuer>
		<Signature Id="Signature2">
			<SignedInfo>
				<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512" />
				<Reference URI="#id-YVzIltmHVtIUHgMy0">
					<Transforms>
						<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
						<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					</Transforms>
					<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512" />
					<DigestValue>
						IyuAbQ2ATYeBZZgk/+oTFumLajLZBa5MnmzM8q0x7Zo7ZPVXmDFCoE1GtZzxvPi0
						vCdyvyoaUlLqb6QOIfRf7w==
					</DigestValue>
				</Reference>
			</SignedInfo>
			<SignatureValue>
				OGIjmLVh4vevrh9Q+5z83T2epm/fs2pCZekzHH40ea0F+P97kCzmz+HwMafdTnSs
				hsqIxCc5mneZt07r+jAQr0gqxk+GOIunC+W2m1STCMLNQzGJRomcyKfLgdYFARQZ
				kbUAYufibTGkOvli9sY5tee718964GmWxrnDQV6W7jXsxabtZ1OXx4qL69VYVPaG
				h64vuJ///vms1dNMYuTVMr17QA1CdJKoJET3WEj8v0fJpJC6KdDaQuvcpdZ+UXEt
				sXya10IKJ6M5X7OSyIMz3i5d+VK5YZ2rK0qD/uZJusqdy9awxXJbGMBBclTF/1GV
				FQq+X1Z6uDFwQfGRouyeNw==
			</SignatureValue>
			<KeyInfo>
				<X509Data>
					<X509Certificate>
						MIIDiDCCAnCgAwIBAgIJAJnqANY7GvtNMA0GCSqGSIb3DQEBCwUAMFkxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTERMA8GA1UECgwIdGVzdGVudjIxGDAWBgNVBAMMDyR7YW5zaWJsZV9mcWRufTAeFw0xODA3MTkxMzEwMDVaFw0xOTA3MTkxMzEwMDVaMFkxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTERMA8GA1UECgwIdGVzdGVudjIxGDAWBgNVBAMMDyR7YW5zaWJsZV9mcWRufTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALTPycItk7xvubL0WgegvbtCvhzeCq13WorzjYQdpWvUwY8YmL51h6ssKfWMfnSj96IxlJw2HTm+TgHK2/S7Iw7gh6xoaY+LDmkZGJKzUSFR/Hn7WbFNb3jytowiNDQdcBZdhNhEnDvd2fLMGxD81qdlMx3y5XHP+p9Gc8bjp8aShGw+DQpWBXcfoDnCXz5ywmnRoD66CnMFMQXmD0wZf79/0fY+Muwn83r7P0h6bJCFDjPdGiSeo7q5AJKkERoNoedcHThCuT0uN36bDaVBIcSxVtPjvVhfcNIVN5JHaCLZT89aU8DAJlTUiO3u5Nj4aDjDXAhxMWkwGbHXCznhjVMCAwEAAaNTMFEwHQYDVR0OBBYEFH1/ReU+04oYtVpMgD/zVCPuagu6MB8GA1UdIwQYMBaAFH1/ReU+04oYtVpMgD/zVCPuagu6MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAAWT9+r+ojVmxUUZvq8/TumEX9Y0FxxQebTcPMeumA58mp9kDCeNK73PZ6cbQSGXzwbNmHw48N2kZMl3rS8ddYPG3nFxEZO5Xi0De2SLGwLZX43lfD4BHhhqhTlnBK8cL+LvySQ32X1vL8aKly/UTez3/DCrdTqFjp1V0PdY2q0Ni3UAiO90MpFGbP+aAQ1LGtI0EWpDCVAqqgAA2EA+s0AlwbC5cuDbQUjHA5dhkWT/4kvHB/E5zPZUtRV4d3mYBs33lfIyKXWjjgR4T8j01wMk2LWCnBU8i4mCb1w3v94KcRbnK23bJLz+zNp6I3belhLknSahyjKPl+6FBSyW/GE=
					</X509Certificate>
				</X509Data>
			</KeyInfo>
		</Signature>
		<Subject>
			<NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" NameQualifier="http://idp.simevo.com:8088" SPNameQualifier="http://sp2.simevo.com:8000/metadata.php">
				a49d0ad1a26fc392c4a079e49e9e921598c75cd6e817c5ccbbc025efacf2f948
			</NameID>
			<SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<SubjectConfirmationData InResponseTo="ONELOGIN_59cf261e287c157f7ab04883684820cdee82d551" NotOnOrAfter="2018-07-21T14:13:06Z" Recipient="http://sp2.simevo.com:8000/index.php?acs" />
			</SubjectConfirmation>
		</Subject>
		<Conditions NotBefore="2018-07-21T13:13:06Z" NotOnOrAfter="2018-07-21T14:13:06Z">
			<AudienceRestriction>
				<Audience>
					http://sp2.simevo.com:8000/metadata.php
				</Audience>
			</AudienceRestriction>
		</Conditions>
		<AuthnStatement AuthnInstant="2018-07-21T13:13:06Z" SessionIndex="id-xlpneRaI7RugChANX">
			<AuthnContext>
				<AuthnContextClassRef>
					https://www.spid.gov.it/SpidL1
				</AuthnContextClassRef>
				<AuthenticatingAuthority>
					https://www.spid.gov.it/SpidL1
				</AuthenticatingAuthority>
			</AuthnContext>
		</AuthnStatement>
		<AttributeStatement>
			<Attribute FriendlyName="name" Name="urn:mace:dir:attribute-def:name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Moreno
				</AttributeValue>
			</Attribute>
			<Attribute Name="companyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Moretti-Ricci s.r.l.
				</AttributeValue>
			</Attribute>
			<Attribute Name="gender" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					M
				</AttributeValue>
			</Attribute>
			<Attribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Piras
				</AttributeValue>
			</Attribute>
			<Attribute Name="birthDate" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					1975-04-21
				</AttributeValue>
			</Attribute>
			<Attribute Name="registeredOffice" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					Stretto Ferrara 871 Appartamento 85
					Settimo Emanuel, 71694 Forlì-Cesena (FM)
				</AttributeValue>
			</Attribute>
			<Attribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					e6edd069-345c-9ec0-9655-d75365260ba0
				</AttributeValue>
			</Attribute>
			<Attribute FriendlyName="email" Name="urn:mace:dir:attribute-def:email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">
					gabrielefontana@vitale.org
				</AttributeValue>
			</Attribute>
		</AttributeStatement>
	</Assertion>
</Response>
```

**Comment by fmarco** [comment]
@lorenzocattaneo non riesco a riprodurre l'errore (testato su python 2 e python 3). L'hai ottenuto su master aggiornato?

**Comment by simevo** [comment]
io riproduco così:
```
$ python --version
Python 2.7.15
$ python q.py
Traceback (most recent call last):
  File "q.py", line 12, in <module>
    xml = prettify_xml(response)
  File "q.py", line 6, in prettify_xml
    msg = etree.tostring(etree.XML(msg.encode('utf-8')), pretty_print=True, encoding='utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5911: ordinal not in range(128)
```
il carattere 5911 è: ì di Forlì
[rq.zip](https://github.com/italia/spid-testenv2/files/2224714/rq.zip)

**Comment by fmarco** [comment]
@lorenzocattaneo potresti riprovare? Ho pushato un minfix su master.

**Comment by lorenzocattaneo** [comment]
@fmarco mi sembra tutto a posto!
