### ISSUE TITLE
LogoutRequest: attributo Destination non validato correttamente

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#85]
Inviando questa LogoutRequest:

```xml
<saml2p:LogoutRequest Destination="http://localhost:8088/sso" Version="2.0" ID="_148fc7c95e0f709c6b8e2b74c4630546" IssueInstant="2018-07-21T18:00:44Z" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://www.prova.it/">https://www.prova.it/</saml2:Issuer><saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" NameQualifier="http://localhost:8088">ec7ff0a108ed34f7d2cf589741dab04677c1a1c76041589b17058d1245fecfd1</saml2:NameID><saml2p:SessionIndex>id-lmNwaJeHt2iobIWbZ</saml2p:SessionIndex></saml2p:LogoutRequest>
```

ottengo il seguente errore dal testenv2:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 1287, in single_logout_service
    req_info = self.server.parse_logout_request(saml_msg['SAMLRequest'], _binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/entity.py", line 1198, in parse_logout_request
    "single_logout_service", binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/entity.py", line 857, in _parse_request
    _request = _request.verify()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/request.py", line 100, in verify
    return self._verify()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/request.py", line 88, in _verify
    raise OtherError("Not destined for me!")
saml2.s_utils.OtherError: Not destined for me!
```

Questo è lo stralcio dei metadati IdP restituiti da `/metadata` del testenv2:

```xml
<ns0:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8088/slo"/>
<ns0:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8088/slo"/>
```

Quindi il valore indicato nella LogoutRequest è corretto.

**Comment by alexrj** [comment]
È presente ancora nell'attuale master.

**Comment by alexrj** [comment]
Confermo, risolta
