### ISSUE TITLE
AuthnRequest: errore "KeyError: 'binding'"

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#89]
Inviando questa AuthnRequest:

```xml
<saml2p:AuthnRequest ForceAuthn="false" IssueInstant="2018-07-24T17:15:47Z" Version="2.0" Destination="http://localhost:8088/sso" ID="_b09d06c33ba8649e14b34421d5a5d102" AttributeConsumingServiceIndex="1" AssertionConsumerServiceIndex="0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://www.prova.it/">https://www.prova.it/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

ottengo il seguente errore:

```
Traceback (most recent call last):
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/spid-testenv.py", line 1020, in single_sign_on_service
    atcss = self.server.metadata.attribute_consuming_service(sp_id)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/mdstore.py", line 1108, in attribute_consuming_service
    "attribute_consuming_service", binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/mdstore.py", line 978, in service
    srvs = _md.service(entity_id, typ, service, binding)
  File "/Users/alranel/Documents/git/TD/spid-testenv2/env/lib/python3.7/site-packages/saml2/mdstore.py", line 575, in service
    if srv["binding"] == binding:
KeyError: 'binding'
```

**Comment by alexrj** [comment]
Se può essere utile aggiungo uno stralcio dai metadati SP:

```xml
        <md:AssertionConsumerService  
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"  
            Location="http://localhost:3000/spid-sso"  
            index="0"  
            isDefault="true" /> 

        <md:AttributeConsumingService index="1"> 
            <md:ServiceName xml:lang="it">Servizio</md:ServiceName> 
            <md:ServiceDescription xml:lang="it"></md:ServiceDescription> 
            <md:RequestedAttribute Name="fiscalNumber" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/> 
            <md:RequestedAttribute Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/> 
            <md:RequestedAttribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/> 
            <md:RequestedAttribute Name="dateOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/> 
        </md:AttributeConsumingService> 
```

**Comment by fmarco** [comment]
@alexrj fixato in #90
